#!/bin/sh
# as long as i couldnt get 400-wireguard running

touch /etc/config/wireguard

uci set wireguard.wireguard=wireguard

uci set wireguard.wireguard.enabled=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.enabled')
uci set wireguard.wireguard.iface=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.iface')
uci set wireguard.wireguard.v6=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.v6')
uci set wireguard.wireguard.v4=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.v4')
uci set wireguard.wireguard.batman=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.batman')
uci set wireguard.wireguard.ownip=fdf1::$(cat /sys/class/net/eth0/address|awk 'BEGIN{FS=":"}{print $1$2":"$3$4":"$5$6}')
# empty strings are not working like following
# uci set wireguard.wireguard.secret=$(cat /root/wg_privatekey)
uci set wireguard.wireguard.port=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.port')
uci set wireguard.wireguard.limit=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.limit')
uci set wireguard.mesh1=peer
uci set wireguard.mesh1.enabled=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.peer.mesh1.enabled')
uci set wireguard.mesh1.PublicKey=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.peer.mesh1.PublicKey')
uci set wireguard.mesh1.gretapip=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.peer.mesh1.gretapIP')
uci set wireguard.mesh1.Endpoint=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.peer.mesh1.Endpoints')
uci set wireguard.mesh1.AllowedIps=$(cat /lib/gluon/site.json| jsonfilter -e '$.wireguard.peer.mesh1.AllowedIps')

uci commit wireguard
